// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddNPCToSettlement(arg1, arg2, arg3) {
  return window['go']['main']['WailsAPI']['AddNPCToSettlement'](arg1, arg2, arg3);
}

export function AddRandomNPCToSettlement(arg1) {
  return window['go']['main']['WailsAPI']['AddRandomNPCToSettlement'](arg1);
}

export function AddRandomNPCsToSettlement(arg1, arg2) {
  return window['go']['main']['WailsAPI']['AddRandomNPCsToSettlement'](arg1, arg2);
}

export function CreateRandomSettlement() {
  return window['go']['main']['WailsAPI']['CreateRandomSettlement']();
}

export function CreateRandomSettlementWithNPCs(arg1) {
  return window['go']['main']['WailsAPI']['CreateRandomSettlementWithNPCs'](arg1);
}

export function CreateSettlement(arg1) {
  return window['go']['main']['WailsAPI']['CreateSettlement'](arg1);
}

export function DeleteAllNPCsFromSettlement(arg1) {
  return window['go']['main']['WailsAPI']['DeleteAllNPCsFromSettlement'](arg1);
}

export function DeleteAllSettlements() {
  return window['go']['main']['WailsAPI']['DeleteAllSettlements']();
}

export function DeleteNPCFromSettlement(arg1, arg2) {
  return window['go']['main']['WailsAPI']['DeleteNPCFromSettlement'](arg1, arg2);
}

export function DeleteSettlement(arg1) {
  return window['go']['main']['WailsAPI']['DeleteSettlement'](arg1);
}

export function GetCreationOptions() {
  return window['go']['main']['WailsAPI']['GetCreationOptions']();
}

export function GetNPC(arg1) {
  return window['go']['main']['WailsAPI']['GetNPC'](arg1);
}

export function GetSettlement(arg1) {
  return window['go']['main']['WailsAPI']['GetSettlement'](arg1);
}

export function ListSettlements() {
  return window['go']['main']['WailsAPI']['ListSettlements']();
}

export function RollSpeciesName(arg1) {
  return window['go']['main']['WailsAPI']['RollSpeciesName'](arg1);
}

export function RollSubtypeFields(arg1) {
  return window['go']['main']['WailsAPI']['RollSubtypeFields'](arg1);
}

export function SaveNPC(arg1) {
  return window['go']['main']['WailsAPI']['SaveNPC'](arg1);
}

export function UpdateSettlement(arg1) {
  return window['go']['main']['WailsAPI']['UpdateSettlement'](arg1);
}
