// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {mapper} from '../models';
import {controllers} from '../models';
import {main} from '../models';

export function AddNPCToSettlement(arg1:string,arg2:string,arg3:string):Promise<mapper.SettlementView>;

export function AddRandomNPCToSettlement(arg1:string):Promise<mapper.SettlementView>;

export function AddRandomNPCsToSettlement(arg1:string,arg2:number):Promise<mapper.SettlementView>;

export function CreateRandomSettlement():Promise<mapper.SettlementView>;

export function CreateRandomSettlementWithNPCs(arg1:number):Promise<mapper.SettlementView>;

export function CreateSettlement(arg1:mapper.SettlementCreateInput):Promise<mapper.SettlementView>;

export function DeleteAllNPCsFromSettlement(arg1:string):Promise<mapper.SettlementView>;

export function DeleteAllSettlements():Promise<void>;

export function DeleteNPCFromSettlement(arg1:string,arg2:string):Promise<mapper.SettlementView>;

export function DeleteSettlement(arg1:string):Promise<void>;

export function GetCreationOptions():Promise<controllers.CreationOptions>;

export function GetNPC(arg1:string):Promise<mapper.NPCInput>;

export function GetSettlement(arg1:string):Promise<mapper.SettlementView>;

export function ListSettlements():Promise<Array<mapper.SettlementView>>;

export function RollSpeciesName(arg1:string):Promise<string>;

export function RollSubtypeFields(arg1:string):Promise<main.SubtypeRoll>;

export function SaveNPC(arg1:mapper.NPCInput):Promise<mapper.NPCInput>;
