// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {controllers} from '../models';

export function AddNPCToSettlement(arg1:string,arg2:string,arg3:string):Promise<main.SettlementView>;

export function AddRandomNPCToSettlement(arg1:string):Promise<main.SettlementView>;

export function AddRandomNPCsToSettlement(arg1:string,arg2:number):Promise<main.SettlementView>;

export function CreateRandomSettlement():Promise<main.SettlementView>;

export function CreateRandomSettlementWithNPCs(arg1:number):Promise<main.SettlementView>;

export function CreateSettlement(arg1:main.SettlementCreateInput):Promise<main.SettlementView>;

export function DeleteAllNPCsFromSettlement(arg1:string):Promise<main.SettlementView>;

export function DeleteAllSettlements():Promise<void>;

export function DeleteNPCFromSettlement(arg1:string,arg2:string):Promise<main.SettlementView>;

export function DeleteSettlement(arg1:string):Promise<void>;

export function GetCreationOptions():Promise<controllers.CreationOptions>;

export function GetSettlement(arg1:string):Promise<main.SettlementView>;

export function ListSettlements():Promise<Array<main.SettlementView>>;
